"""empty message

Revision ID: 5bdc7bf20269
Revises: 
Create Date: 2022-08-07 17:08:42.736273

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5bdc7bf20269'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=1024), nullable=False),
    sa.Column('shortened_url', sa.String(length=50), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_url'),
    sa.UniqueConstraint('shortened_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_model')
    # ### end Alembic commands ###
